### ISSUE TITLE
leetcode 125 isPalindrome

### ISSUE THREAD

**Issue by speedcell4** [magicpieh28/leetcode#1]
## your problem

you did not notice the word `alphanumeric`, which means English letters or numbers. so your regular expression should be `[0-9a-zA-Z]`. this modification is enough to get an `accepted`.

### `str`

in addition, python's build-in type `str` has a method which called `isalnum`, so you don't need regular expression, just call `isalnum`.

for more methods of `str`, you may need to check the [official document](https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str), please notice there are something methods start with `is`, they are all used to just some property.

if you don't like read document, open you PyCharm, write a `str` and put a dot after it, then popout will list you all the available methods. 
![image](https://user-images.githubusercontent.com/3585459/49559043-98240f00-f950-11e8-9a39-68eabf83d850.png)

### `list`

`list` can compare with other `list`, the rules shows like below

1. lists which have different length are not equivalent
2. lists which have different elements in the corresponding position are not equivalent
3. if none of (1) or (2), these two lists are equivalent

```python
def list_compare(a, b):
    if len(a) != len(b):
        return False
    for x, y in zip(a, b):
        if x != y:
            return False
    return True
```

you will notice `list_equivalent` is the same thing as Python build-in rules `==`.

```python
def list_equivalent(a, b):
    if len(a) != len(b):
        return False
    for x, y in zip(a, b):
        if x != y:
            return False
    return True


print(list_equivalent([1, 2, 3], [1, 2]))
print(list_equivalent([1, 2, 3], [1, 2, 3]))
print(list_equivalent([1, 2, 3], [1, 4, 3]))

print([1, 2, 3] == [1, 2])
print([1, 2, 3] == [1, 2, 3])
print([1, 2, 3] == [1, 4, 3])
```

at the same time, python defines how to just which list is greater, which is lesser. the same rule just replace the `!=` part with `<=` and without length comparing

```python
def list_greater(a, b):
    for x, y in zip(a, b):
        if x <= y:
            return False
    return True
```

and not only the `list`, `tuple` and `str` can also be compared (`==`, `!=`, `>`, `>=`, `<`, `<=`). the rules above we call them [lexicographical order](https://ko.wikipedia.org/wiki/%EC%82%AC%EC%A0%84%EC%8B%9D_%EC%88%9C%EC%84%9C) and for how to compare the single character in a string, you may need to [ASCII code](https://ko.wikipedia.org/wiki/ASCII) and its extension [Unicode](https://ko.wikipedia.org/wiki/%EC%9C%A0%EB%8B%88%EC%BD%94%EB%93%9C)

## compact answer

after understanding all these things above, you can write something like

```python
class Solution:
    def isPalindrome(self, s):
        a = [x.lower() for x in s if x.isalnum()]
        return a == a[::-1]
```

## tips

split your code into small functions, don't just write a huge script for all what you want to do

**Comment by magicpieh28** [comment]
ありがとうございます！でもisPalindrome自体はそこまで長くないコードなのにこれも細かく分けたほうがいいということなの？
