### ISSUE TITLE
leetcode 20 isValid

### ISSUE THREAD

**Issue by speedcell4** [magicpieh28/leetcode#2]
## comment

your solution is correct, but the aim of this problem is the data structure called [stack](https://ko.wikipedia.org/wiki/%EC%8A%A4%ED%83%9D)

read my code below after you figure out what is stack.
and by the way, read something about another data structure whose name is `queue`

```python
class Solution(object):
    def isValid(self, s):
        stack = [None]
        for x in s:
            if x in '([{':
                stack.append(x)
            elif x == ')' and stack[-1] == '(':
                stack.pop()
            elif x == ']' and stack[-1] == '[':
                stack.pop()
            elif x == '}' and stack[-1] == '{':
                stack.pop()
            else:
                return False
        return len(stack) == 1
```

**Comment by magicpieh28** [comment]
So, I can use stack(LIFO) structure with 'from queue import Lifoqueue'. And I can use queue(FIFO) structure with 'from queue import Queue'. Or also I can use those as like you. Am I right?

**Comment by speedcell4** [comment]
> I can use stack(LIFO) structure with 'from queue import Lifoqueue'. 

yes

> And I can use queue(FIFO) structure with 'from queue import Queue'

yes, but Queue can not be used in this problem

>  Or also I can use those as like you.

yes
