### ISSUE TITLE
leetcode 58 lengthOfLastWord

### ISSUE THREAD

**Issue by speedcell4** [magicpieh28/leetcode#3]
## comment

why do you think you need for-loop?
actually, you only need to consider the empty string case and non-empty string case

```python
class Solution:
    def lengthOfLastWord(self, s):
        res = s.split()
        return len(res[-1]) if len(res) else 0
```

**Comment by magicpieh28** [comment]
!!!

**Comment by magicpieh28** [comment]
But your code raises IndexError, so I fixed it. Please check if you have a time.

**Comment by speedcell4** [comment]
But I actually got `accepted` with that code, could you please show me your input, which raised `IndexError`?

**Comment by magicpieh28** [comment]
'         '

**Comment by speedcell4** [comment]
no, that is an invalid input, according to problem description
> Given a string s consists of upper/lower-case alphabets and empty space characters ' ', return the length of last word in the string.

there is no empty string in the input data, so I don't need to consider about that
